#![allow(clippy::expect_used, clippy::panic, clippy::unwrap_used)]

//! Embed every file under `schemas/` into the binary.
//!
//! Doc 10 principle 4: schema at every boundary, validated on entry. That only
//! holds if the schemas ship with the binary rather than being loaded from a
//! path a user could edit or delete. Walking the directory at build time means
//! adding a schema file is drop in: no registration list to keep in step.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let schemas = manifest
        .join("../../schemas")
        .canonicalize()
        .expect("the schemas directory must exist beside the workspace root");

    println!("cargo:rerun-if-changed={}", schemas.display());

    let mut files = Vec::new();
    collect(&schemas, &mut files);
    files.sort();

    let mut out = String::from(
        "// Generated by build.rs. Do not edit.\n\
         /// Every schema file, as (path relative to schemas/, contents).\n\
         pub static EMBEDDED: &[(&str, &str)] = &[\n",
    );
    for path in &files {
        println!("cargo:rerun-if-changed={}", path.display());
        let rel = path
            .strip_prefix(&schemas)
            .expect("under schemas/")
            .to_string_lossy()
            .replace('\\', "/");
        writeln!(
            out,
            "    ({rel:?}, include_str!({:?})),",
            path.to_string_lossy().replace('\\', "/")
        )
        .expect("write");
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("embedded.rs");
    std::fs::write(dest, out).expect("write embedded.rs");
}

fn collect(dir: &Path, into: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(&path, into);
        } else if path.extension().is_some_and(|e| e == "json") {
            into.push(path);
        }
    }
}
